### PR TITLE
Improved boot script

### PR DESCRIPTION
**Pull request by mathuin**
I've been tinkering with a boot script which works well with multicore
and has a separate install script to keep the boot script clean.

This code, while flight-tested, is most definitely not yet ready for merging!

I am looking for feedback and suggestions for improvement.  Thank you!

### CODE REVIEW

**Comment by ghost** [comment]
Looks good, could use boot/README.md update (and you can change the line with `launch_asc(120000)` if you approve my change to km in launch/_asc/_stto). There is logic with tags regarding the startup files, should be mentioned there.

I have noticed that you have removed bootConsole/Warning/Error. Well, not sure about that. Maybe `lib_ui` should be prioritized, extra install first, then use it or fail immediatelly.

**Comment by mathuin** [comment]
You make a great point with regard to updating the documentation, especially with the bits about tags.

Removing the boot versions of Console/Warning/Error was due to space.  I have no major attachment to this change.  Those three functions represent 20% of the script's total length.  I'm usually watching the launch CPU like a hawk during takeoff, so I don't personally need the warble or red UI banner -- but it's not all about me.  If *you* like launching without cluttering your display with kOS terminal windows, then the warning/error notifications have value and they should come back.

**Comment by ghost** [comment]
I don't care much about printouts, terminal is enough for me, the rest is cosmetic, not up to me to decide.
I definitelly like the `install.ks`, but again, the rest (booting) is not for me to review, at least not now. I am still more interested in basic scripts (launch, circularize, transfer, rendezvous, dock etc.).

**Review by ghost — COMMENTED** [review]
Like the documentation update, especially the part mentioning named cores.

@xeger should approve this, becase he is currently working on it, see his `install` branch

**Comment by mathuin** [comment]
Alas, @xeger, I didn't realize I was stepping on your toes when I started this. :-)  If you prefer your approach, just let me know!

**Comment by xeger** [comment]
I made some progress on `install` but haven't done any testing yet. Given that you're wiling to put the time into it, I have no problem going with your solution if the two of you manage to get something working that's mutually agreeable.

The main reason for UI banners during boot was to avoid confusing kOS/RAMP newbies by giving them a clear indication when something's gone wrong. Nothing worse than following the README instructions and not seeing any visible signs of an autopilot. Nevertheless, it might be overkill

Something that I was playing with in my `install` branch was to _overwrite_ the boot script with the mission script once install has done its work successfully, rendering the size of the boot script irrelevant. It's easy to do in principle: test the contents of the boot volume; if only one script is found then it _must_ be the boot script itself, install RAMP, then and copy designated startup script over top of boot script and reboot.

**Comment by mathuin** [comment]
The overwrite-boot-with-mission is a great idea.  I haven't tested it yet, but I bet you don't even have to test the volume's contents -- just set https://ksp-kos.github.io/KOS/structures/vessels/kosprocessor.html#attribute:KOSPROCESSOR:BOOTFILENAME to the startup script name and reboot!

**Comment by mathuin** [comment]
That actually worked.  I'm impressed!  The first executable line in the script is `CORE:VOLUME:DELETE(CORE:BOOTFILENAME).` to maximize the room for incoming files. In fact, the total space and bytes free values are the same!

If the startup script is found, then `SET CORE:BOOTFILENAME TO StartupScript. REBOOT.` does exactly what you'd expect.  I just learned that my code does *not* support not finding the script, so that's my next tinkering project. :-)

**Comment by mathuin** [comment]
@xeger I've finished my tweaks, let me know if you like this or if you'd rather I port just the deletion code to the existing boot script.

**Comment by mathuin** [comment]
Oh, and a question for you -- what's the history behind the RAMP scripts being in the root of the repository but in `./ramp/` in the script directory?  If the scripts were in the subdirectory in the repo, it'd be possible to stick the repo itself in `Ships/Script` which would make testing changes a heck of a lot easier. :-)

**Review by xeger — APPROVED** [review]

**Comment by xeger** [comment]
Hi @mathuin; sorry for being unresponsive for so long! Do you still play KSP? Have you enjoyed your install changes?

Someone else recently opened an issue complaining that RAMP has become abandonware. I promised him that I would reinstall KSP over the holidays and spend a little time focusing on usability. Obviously, your install stuff would really help there.

**Comment by mathuin** [comment]
I have not played KSP since purchasing the expansions (ironic, I know) but if kOS is up to date with the most recent KSP I will put some time this week into testing these changes.  I will check with the kOS Discord tonight and let you know here what they have to say.

**Comment by mathuin** [comment]
Okay, kOS has been updated to work with 1.8.1!

* Reinstalled KSP, CKAN, and kOS and Trajectories.
* Copied the code from this branch into place.  
* Added the patch to increase device capacity.  
* Made a copy of the stock Kerbal 1 craft with the HAL-like kOS widget, named it Kerbal 2.
* Copied `mission/lko.rs` to `start/Kerbal 2.ks`.
* Launched the craft.  Jeb made it to orbit.
* Did the same with the stock Kerbal X craft and `mission/mun.ks`.
* Launched the craft.  Val, Bill and Bob never made their injection burn, but I blame the Kerbal X design. :-)

The boot script still works as advertised.  I did not test the per-core changes as I have misplaced the vessel for which the code was designed, but that code is pretty stable.

Due to changes in my employment, I can't send any more pull requests without a note from work.  I will see what I can do about making that happen after the holidays.

**Pull request merged**
