### PR TITLE
Tests, Launch improvements and fixes

### PR DESCRIPTION
**Pull request by ghost**
I would like to add some tests, that we can all see what individual parts are doing and make sure everything works. Every test rocket/ship/script should either auto-boot and do what is needed or include MD description of same name (will do that later).

The rocket is overcomplicated on purpose and already revealed some problems I will address soon:

1. Staging of booster+tank combo needed better logic - boosters are no longer treated as engines but as tanks. But as I am writing this I also realized this could cause problems on its own - if normal engines are flamed out, they won't wait for the boosters to flame out, damn, will think about that.

2. Launch script needs improvements. I have my own launch script, will try to get the best of both.

3. NOAUTO not working as expected. I did some test when pushing it, worked, but not with this test twin. Will fix that too.

P.S.: Should I change lib_parts so that it also performs actions/events on parts with same tag as executing core if no tag provided (or empty)?

### CODE REVIEW

**Comment by ghost** [comment]
I have fixed few things, those can be merged, but I would like you to test the launch script and give me feedback. It is a bit more agressive, but can launch things that original script could not (e.g. that StagingTest).

1. Throttle limit: well, it does not seem to work properly, maybe limit based on TWR? Somebody knows the formula for heating based on speed and altitude/pressure?
2. Ascent parameters - midAlt, midAng and profile, try playing with it a bit, please.

**Comment by ghost** [comment]
Now I am satisfied, waiting for review.

**Comment by mathuin** [comment]
Wow, that staging test rocket *is* complicated!  Here's what I observed:

* The Hammers staged immediately after the FL-T200 tanks on them were empty.
* The Sparks were released immediately after the Oscars emptied.
* The Swivel only dropped when its tank was empty.
* The Fleas flamed out before the Terrier after which all three staged.
* The fairing was deployed immediately after the three staged.
* The Spark under the fairing started about half a second later.
* The bro-tagged antenna only deployed when the bro core was used, not when sis was used.
* Both lower panels and the other antenna deployed.
* None of the upper probe's stuff deployed.

The launch script is a lot chattier, I suspect for debugging purposes.  Very interesting stuff!  The fairings got really hot when the Fleas kicked in, so that's probably a good place to worry about throttle limits with respect to heat.

**Comment by mathuin** [comment]
With respect to your comment on lib_parts and actions on parts with matching tags:  I think that with few exceptions anything that's a wrapper to `partsDoEvent` and `partsDoAction` should have a tag parameter which is passed to those functions.  `partsExtendSolarPanels` is a good example.  If you're interested in adding wrappers for other components like decouplers, I definitely think you should have a tag parameter.  Fairings are pretty much the only exception, because their removal seems to be a function of "have we gone to space today or not" which is much different than solar panels and decouplers I think.

**Comment by mathuin** [comment]
LaunchThrottle failed the first launch, spinning around 14k after Hammers flamed out.  Worked fine the second launch.  Nice job with the staging!

LaunchWeak also failed the first launch, with a strong shimmy which started at about 3k when the warp began and then got significantly worse at around 12k after SRBs were released.  The apoapsis never passed about 49k before coming back to Kerbin.  The second launch topped off around 50k, same fate. 
 Third did the same. :-(

**Comment by mathuin** [comment]
I also launched some of my more fussy missions with your changes.  In general, the launch seems to be a little more fuel-efficient, as I end up with a little more gas in the tank when I get to orbit.

The multi-core equatorial relay mission had some minor difficulties with the second and third deployments, though the launch and first deployment were flawless.  Those two deployments have burns, and they had burn faults of 0.1 m/s.  Their orbit speeds are 1010.0 m/s as compared to the first deployment's speed of 1010.8 m/s.

My SCANsat mission caused an exception to be thrown when staging during the launch.  The exception wasn't logged, but I have reproduced it here:

```
Tried to push NaN into the stack.
At 1:/launch_asc.ks, line 52
orbMul*sqrt(body:mu/(body:radius+max(topAlt,alti
tude)))-midSpd))^profile)).

                ^
Called from 1:/launch_asc.ks, line 135
lock steering to ascentSteering().
```

If you know a way to log those, please let me know -- `logconsole` in `lib_ui.ks` was set to `True` but to no avail.  I can send you the craft and script files if you want to reproduce it, and I'm willing to iterate through a few times with you as well.

**Comment by ghost** [comment]
**StagingTest:** it always does what I intended in my tests. Launching to 200km flames out Terrier and Fleas almost at the same time, but when launching to 72km (which overshoots to 76,7), Fleas flame out earlier but Terrier not staged until it's FL-T200 is empty. As expected. The printout reads `Stage 4/2 ... Tanks: 3 Engines: 3` which means that it will stage when all three engines flame out or all three tanks (booster as tank as well) are empty, which is practically the same condition. **Fairings never got hot**. Are you using some mods?

**LaunchThrottle:** throttles down to 30% around 1000m, printout is `Speed: 281/200 Q:37+74`. That is somewhere around super-sonic transition. Throttle back when Hammers flame out, 12km, last printout was `Speed: 671/298 Q:66+17` which looks like Max-Q. Next was `Speed: 725/854 Q:23+5` because pressure dropped to 5% and Q:23% due to both low air pressure and lower thrust when Hammers are off.

Second slowing occurs at 30km, slow throttle-down, air is getting hot but no big problem, speed 1400 at 33.3km. Reaches 200km apsis at 58km altitude, engines off.

Second test was almost the same, throttle at 30% from 1km to 12km, Q:37+74, 60+43, 66+17, 23+5. I can repeat that as many times as I want, always the same.

Third test to 75km: Hammer throttle-down exactly the same. Minor problem at 33km, when engines are off and the rocket spins down, but the script ignites the engines again and compensates. Looks bad but the rocket makes it to orbit.

**LaunchWeak:** everything is fine until 43km when Poodle with TWR 0.66 is staged. Pitch 35°, Prograde 15°. Script barely compensates at 57km, when prograde is like 3°, looks like 0° at 60km, but makes it. Horizontal at 63km, it starts to fall few meters but achieves circular *orbit*, raises apoapsis and makes it.

Will look at the rest later.

**Comment by ghost** [comment]
`lib_parts`: added few tags, make PR to my fork if you want more. Purposedly left `partsMMEngineClosedCycle` and `partsMMEngineAirBreathing` unchanged.

`LaunchXXX`: ahh, I think I know what is going on: I AM USING MOD: KerbalJointReinforcement (and WorldStabilizer), that is probably it. I should add some struts (and/or auto-struts) to the rockets.

**Comment by ghost** [comment]
Couldn't reproduce the problems even after uninstalling JointReinforcement. LaunchWeak wobbled a lot at 4th stage, so, added *grandparent* autostruts (needs Advanced Tweakables to access, should work without it, you just won't see it). No problems with LaunchThrottle, small wobbling of Hammers, added some classic struts as well + some more inside fairings.

As for NaN: probably divide by zero, cannot see it now, will look into it when I have more time.
As for inaccuracy: you know I have improved the accuracy of node+circ scripts a lot, right? Still not enough? Well, I do plan to look at the circ.ks again to achieve e=0.0001 even if nodes are used.

**Comment by ghost** [comment]
Regarding NaN: Can you reproduce it? What was the altitude and speed? Cannot see where it could divide by zero:
```
		set pitch to arccos(midCos+(1-midCos)*min(1,((speed-midSpd)/max(1,
		orbMul*sqrt(body:mu/(body:radius+max(topAlt,altitude)))-midSpd))^profile)).
```
`body:radius+max(topAlt,altitude)` cannot be zero,
`max(1,...)` cannot be zero either,
`speed-midSpd` could potentially become negative, so `max(0,...)` could fix that, but that should still not be a problem, the result of arccos would be more than 40° but that is not an error.
Maybe it could become a problem if you go really high, where orbital speed is lower than the speed achieved at 21km. Need more info.

P.S.: Nah, launched my test probe directly to 8,000,000m without problems.

**Comment by mathuin** [comment]
With regard to the NaN, it is definitely reproducible.  I broke the pitch expression into separate pieces with partial computations to see exactly where the NaN was thrown.

		set foo1 to max(topAlt,altitude).
		uiConsole("debug","foo1: " + foo1).
		set foo2 to body:radius+foo1.
		uiConsole("debug","foo2: " + foo2).
		set foo3 to body:mu/foo2.
		uiConsole("debug","foo3: " + foo3).
		set foo4 to sqrt(foo3).
		uiConsole("debug","foo4: " + foo4).
		set foo5 to orbMul*foo4.
		uiConsole("debug","foo5: " + foo5).
		set foo6 to foo5-midSpd.
		uiConsole("debug","foo6: " + foo6).
		set foo7 to max(1,foo6).
		uiConsole("debug","foo7: " + foo7).
		set foo8 to ((speed-midSpd)/foo7).
		uiConsole("debug","foo8: " + foo8).
		set foo9 to foo8^profile.

The exception was thrown at `set foo9 to foo8^profile`, which matches the text placement of the caret in the original expression.  Here's the log output at that time:

```
T+119966 debug: foo1: 70000
T+119966 debug: foo2: 670000
T+119966 debug: foo3: 5271044.7761194
T+119966 debug: foo4: 2295.87560118561
T+119966 debug: foo5: 1836.70048094849
T+119966 debug: foo6: 969.665150254444
T+119966 debug: foo7: 969.665150254444
T+119966 debug: foo8: -0.000410913254050042
```

I was thrown for a loop at first because profile is set to 5 above, but when it's actually used it's multiplied by 0.1 making it 0.5 and we all know that taking the square root of a negative number is Bad in kOS. :-)

**Comment by mathuin** [comment]
With regard to inaccuracy: I know your patch touches multiple files, all of which are used by the launches in question.  The burns in question do not use `circ.ks` but instead `run node_apo(nodeapo). run node.` where `nodeapo` is a number based on the body in question and whether it's a synchronous orbit or semi-synchronous orbit.  In this case I think it's changes in `lib_staging.ks` since it's called by `node.ks` but I'm not exactly sure to be honest.

**Comment by mathuin** [comment]
With regard to the test craft:  I really wish it was easier to make an install of KSP with *just* kOS, because that's what we should use for these kinds of tests.  I'm confident they do what you say they do, I'm just puzzled by the NaN coming up with my craft but not yours.

**Comment by ghost** [comment]
1. Speed dropped below midSpd, forgot about the square root (it gives it more juice). Will add that `max(0,speed-midSpd)` around it and that should fix it. You can try.
2. Do you really have the second version of the launch script? The one from first commit could not handle the new test rockets, the latest can. Do you have `ascentSpeedLimit` function there? Do you have the pitch correction `if current < pitch set pitch to min(90,2*pitch-current).`?
3. I use separate copy of KSP with just few mods, mostly informative (Basic DeltaV, Basic Orbit). Removed KerbalJointReinforcement to be as clean as reasonable. No need for install, just make a copy of the game to different folder. (Well, although the new, even more ridiculous, EULA may prohibit this).
4. Staging broke node.ks? Really? Are you sure? Node.ks was never that precise as my circ.ks (after launch). It does not contain the pitch-up logic (to keep apsis where ship is).

P.S.: Or maybe that removed `utilFaceBurn` if your thrust vector is not in line with CoM.

**Comment by mathuin** [comment]
My thrust vector is in line with the center of mass, so I don't think `utilFaceBurn` is involved.  While I hear you about node.ks not being as precise as circ.ks, all I can tell you is that I got no burn faults with the current master branch, and I did with the code in this pull request.

My game time is limited right now, but the next time I start KSP I will ensure I have the latest version of your changes, and I will test your vessels and mine.

**Comment by mathuin** [comment]
Yes, I have `ascentSpeedLimit`.  I added `max(0,...)` around `(speed-midSpd)`, and the exception is no longer thrown.  I did notice the launch start coasting when the apoapsis reached the target height (130k in this example) but the burn to raise periapsis caused the apoapsis to drop to about 125k by the time the periapsis was above Kerbin's surface with the final result of that burn being about 127k by 89k.

The last lines in the kOS window were these:

    Stage 2/0 Delta V: 0 Burn: 0 ISP: 0
    Mass: 2 Dry: 2 Tanks: 0 Engines: 0 TWR: 0
    Stage 1/0 Delta V: 0 Burn: 0 ISP: 0
    Mass: 1 Dry: 1 Tanks: 0 Engines: 0 TWR: 0
    Stage 0/0 Delta V: 2675.9 Burn: 926 ISP: 315
    Mass: 1 Dry: 0 Tanks: 3 Engines: 1 TWR: 0.3

Stage 1 in that craft file is the fairing, so it stands to reason that it would have no real value

The burn ended, and after waiting five and one-half clock minutes (no warp) as the altitude drifted from 116k to about 99k , `circ.ks` decreed the orbit sufficiently circular (e=0.0266) and the mission script moved on.  The master branch's version usually nails this at e=0 for what it's worth.

The transfer script said the burn should be 835.8 m/s, and the node's value was the same.  The estimated burn time was well over five minutes.  For some reason, a few seconds after the burn was complete the engine turned on again and the craft ran out of gas on a trajectory which would take it out of the Kerbal SOI.  I'll try again tomorrow.

1. Any thoughts on why `circ.ks` doesn't actually provide a zero-eccentricity orbit any more?  I think it might be due to the new staging logic, but I didn't have time to go through the code in detail.
2. What's with that additional burn after the transfer injection burn?

**Comment by ghost** [comment]
I highly doubt that staging has anything to do with that, but there was a bug in lib_warp, was it warped? It cannot burn if warped. I have just tested multiple launches to 80,000,000m, ended a bit higher but e=0.0004 (which is rounded by the message to e=0; apo=80,431.6km, peri=80,425.1km).

If you have the updated launch script (with speed limit and pitching-up), then I really don't understand why it does not behave the same for you as for me (LaunchThrottle+LaunchWeak). Realism Overhaul or some mod like this?

No more talking, take the current version (my master) and test it. If it fails then provide the ship and launch script (or at least launch prameters). Cannot fix it if I cannot reproduce it.

**Comment by ghost** [comment]
NOT READY TO BE MERGED! EXPERIMENTS!
I have changed it completely, including `circ` and `node`. `circ` can now circularize anywhere and `node` became universal node executor that does not even need a node, it can take control delegates.

Even added `launch_gui` and tiny helper: `control` (Orbital SAS Gui), try 😄 

Consider this experimental, will probably close this PR without merging,
but will leave it here for a while for comments and ideas.

**Comment by ghost** [comment]
@mathuin The more I think about your problems I cannot reproduce, the more I am convinced that the problem is not in the scripts themselves but rather in the execution, or in better words: in NO execution, freezing. KOS is either not working as expected (low number of instructions per tick - try increasing that, default is 200) or something is eating CPU time, something like big `lock` expression, but I use `unlock all` and cannot reproduce your problems, so, I bet to KOS/performance problems.

BTW: My latest `circ`+`node` should achieve e=0.0000 anywhere, because it is recalculating dV needed for circularization at current position and time. (Assuming KOS does not freeze and does its job.) It, in fact, made the orbit so perfectly circular, that apoapsis and periapsis are jumping when I warp time, KSP is unable to cope with such precision 🤣 (apo=199,764.24m, peri=199,704.51m, that is 60m/200km=0.03% error)

**Pull request closed without merging**
