### PR TITLE
Interplanetary Hohmann

### PR DESCRIPTION
**Pull request by ghost**
EDIT: Originally for node_inc, see next comment for Interplanetary Hohmann

Finally cracked it. This is the proper way to change the inclination - rotate velocity vector around AN-DN link, substract original and finally split to prograde, normal and radial:

```
local v is velocityAt(ship, t1):orbit.
local dv is v*angleAxis(-di,positionAt(ship,t1)-body:position)-v.
local pv is vdot(dv,v:normalized).
local nv is vdot(dv,sn:normalized).
local rv is vdot(dv,vcrs(sn,v):normalized).
```

where `sn` is plane normal vector: `vcrs(ship:velocity:orbit, ship:position-body:position)`
normalized version is same everywhere (perpendicular to orbit plane, mag=1, direction is *up* for prograde orbit).

I hope I did fix all the signs:
```
	set di to vang(sn, tn).
//	fix sign by comparing cross-product to AN/DN vector (the angle is either 0 or 180)
	if vang(vcrs(sn,tn),ln) < 90 set di to -di.
	set ta to vang(sp, ln).
//	fix sign by comparing cross-product to normal vector (the angle is either 0 or 180)
	if vang(vcrs(sp,ln),sn) < 90 set ta to -ta.

```

Tested, but you know, nobody is perfect 😄

### CODE REVIEW

**Comment by ghost** [comment]
Solution for #16
Does not include inclination correction, but I could hit Duna and Jool.
Can target Eve if you add inclination correction, but is not good for moon to moon or for moon to kerbin station. I guess that the sidewise displacement of hyperbolic asymptote from assumed escape vector is too great (original orbit radius is no longer miniscule compared to transfer orbit axis). It would probably need some dV magnitude correction.

P.S.: My thoughts about moon-moon:
1. `r1` needs correction by at least `orbit:semiMajorAxis` but rather some multiple
    or more precisely semiMINORaxis of departure hyperbolic trajectory (is not enough - tested).
2. `body:soiRadius` should be considered as the math assumes
    that `r1` is much much greater than `orbit:semiMajorAxis`
3. Apoapsis of final transfer orbit is *in the past* when we leave SOI,
   that suggests that we could use some angle correction to make apoapsis be exactly at SOI exit

**Comment by ghost** [comment]
fixes #38 let us merge this first (launch_asc and test rockets from #39 not included)

**Comment by mathuin** [comment]
I took a Kerbal X, tossed on a radial kOS node, and gave it a shot.  The version of `launch_asc.ks` from this branch does not handle ground clamps well. :-)  Once I worked around that by popping the clamps by hand, the launch script got me to orbit -- though it did not stage the side bits two by two as they fell empty individually but instead staged the three pairs and the center section only after *everything* was empty.

The circularization script got me e=0.0001 which is great.  The transfer script (which calls `node_hoh.ks`) was able to take me to the Mun and put me in a circular orbit, which is exactly what I expected.  Yay.  Then I did it all over again, but this time I tried to go to Duna.  

My final script for this mission:  `run launch. run node_apo(650000). run node. run circ. set target to body("Duna"). run node_hoh. run node.`.  The increase in orbit altitude was to maximize warp capability.  I had tried the transfer script but it Does Not Like having targets outside its own SoI.  The CPA for the Hohmann node was 145,119km, which is well outside Duna's SoI, so the mission flew right by. :-(

**Comment by ghost** [comment]
**1. Kerbal X:** did stage side bits nicely. You seem to have problems with your KSP/KOS installation. (Too few instructions per physics tick? Too many mods for weak PC? Conflicts? Who knows, you keep reporting non-reproducible problems... cannot reproduce, won't fix).
```
 382873 lib_ui: T=382873
 382875 Stage: 8 Max: 0 DeltaV: 0
 382875 AvISP: 0 TWR: 0 Burn: 0
 382875 ascent: Ascent to 200km; heading 90º
 382875 ascent: Roll: 0°; profile: 5/12
 382882 Stage: 7 Max: 0 DeltaV: 122.5
 382883 AvISP: 270 TWR: 2 Burn: 6
 382883 Alt: 345 Speed: 68/216 Q:2+95 A: 90/90
 382891 Stage: 6 Max: 0 DeltaV: 256.2
 382891 AvISP: 278.8 TWR: 1.9 Burn: 13
 382893 Alt: 1508 Speed: 160/254 Q:12+80 A: 86/79
 382903 Alt: 3535 Speed: 254/326 Q:23+58 A: 75/70
 382906 Stage: 5 Max: 0 DeltaV: 345.3
 382906 AvISP: 294.6 TWR: 2 Burn: 17
 382913 Alt: 6354 Speed: 346/447 Q:30+35 A: 66/62
 382923 Alt: 9961 Speed: 459/616 Q:29+18 A: 58/55
 382926 Stage: 4 Max: 0 DeltaV: 2820.1
 382926 AvISP: 306.3 TWR: 2.1 Burn: 94
 382933 Alt: 14148 Speed: 569/854 Q:20+8 A: 51/47
 382943 Alt: 18951 Speed: 708/1092 Q:12+3 A: 44/39
 382954 Alt: 24267 Speed: 875/1310 Q:7+1 A: 38/30
 382964 Alt: 29932 Speed: 1069/1501 Q:3+0 A: 32/21
 382974 Alt: 35805 Speed: 1291/1649 Q:2+0 A: 27/11
 382984 Alt: 41647 Speed: 1539/1751 Q:1+0 A: 21/0
 382994 Alt: 47095 Speed: 1793/1826 Q:1+0 A: 17/0
 382997 Alt: 48156 Speed: 1844/1840 Q:0+0 A: 16/0
```
...used version from my master, but the difference in lib_stage is only cosmetic, using modified lib_ui, for the printout above.

**2. Duna:** Hohmann script in current RAMP state will warn you about incompatible orbits and give you some random useless node. My version gets you at least close. It is better to use LKO, because it is more efficient (oberth) and more accurate (the higher the ratio orbit:semiMajorAxis/body:soiRadius is, the less accurate it is, because the distance between real SOI exit point and assumed hyperbolic asymptote is bigger). But that can be fixed once you exit SOI and you should make a correction, maybe even two.

**Comment by mathuin** [comment]
I mean no disrespect, but your code does not work.

Brand new installation straight from Steam.  Installed kOS and ModuleManager, no other mods.  Installed RAMP to Ships/Script.  Copied over craft and mission scripts from other stage.  Created brand new game, selected new craft, launched.

Start script attempted to launch, but launch clamps did not release until after center tank emptied.  Pairs of side rockets did not stage when empty, but did stage in pairs when center tank emptied -- exactly like I said before.

As for the Hohmann code, until it works as well as it does for the Mun -- hands-free from orbit to orbit -- it's just not ready.

**Review by mathuin — CHANGES_REQUESTED** [review]
This code does not work.  See comments in pull request for details.

**Comment by ghost** [comment]
Clamps never worked. Fine, I am out of here, good bye. Revert my changes if you like.

**Comment by ghost** [comment]
@xeger I have commited fix for lib_warp to at least leave this repository in relatively working state, but this is end of the road. I cannot fix what I cannot reproduce and this should have been fun and joy, you know, but it is not. I will work on my own scripts that work for me, my work here is done. Use whatever you wish from my repository, scrap the rest, revert what you want, I don't care, but be warned that my repository will dissapear soon, so, you better make a copy if you plan to use anything. Good bye and thank you, I have learned a lot from RAMP.

**Pull request closed without merging**
