### PR TITLE
(Almost) perfect rendezvous, docking and landing

### PR DESCRIPTION
**Pull request by fellipec**
It's reliable enough to do this: https://www.youtube.com/watch?v=FMf3XI_C5Rw
Plus, land dead centre on the runway.

**Changes**

-`boot.ks`: Fixed a condition that can lead to an error if the archive volume is not accessible during boot.
-`deorbitcapsule.ks`: After some advice from people from [Discord ](https://discord.gg/7A5Rhe7)and reading some [nice pages](http://www.braeunig.us/space/orbmech.htm#plnchng) now it can deorbit and land vehicles in airless bodies with great precision. (Maybe substitute land.ks?)
-`deorbitsp.ks`: Adjustments but still WIP.
-`dock.ks`: @xeger 's fix for error "No target selected" after docking.
-`fly.ks`: Reworked stick pusher logic. SHD mode now deprecated. Adjustments to initial glide slope capture logic.
-`lib_util.ks`: Added `utilTo360` function. It just make an arbitrary angle to fall into the 0-360 range. For example, -90 degres became 270.
-`node_hoh.ks`: Now it predicts the time to phi with precision, no more guesswork.
-`node_inc_equ.ks` and `node_inc_tgt.ks`: New component in prograde/retrograde direction prevents the orbit changing shape when changing inclination.
-`transfer.ks` and `warp.ks`: Adjustment in warp.

**Know issue/limitation**

-`node_hoh.ks` is only precise if orbits are almost exactly circular, specially with orbits that have a very large size difference.

### CODE REVIEW

**Comment by fellipec** [comment]
**Changes**

-`boot.ks`: Fixed a condition that can lead to an error if the archive volume is not accessible during boot.
-`deorbitcapsule.ks`: After some advice from people from [Discord ](https://discord.gg/7A5Rhe7)and reading some [nice pages](http://www.braeunig.us/space/orbmech.htm#plnchng) now it can deorbit and land vehicles in airless bodies with great precision. (Maybe substitute land.ks?)
-`deorbitsp.ks`: Adjustments but still WIP.
-`dock.ks`: @xeger 's fix for error "No target selected" after docking.
-`fly.ks`: Reworked stick pusher logic. SHD mode now deprecated. Adjustments to initial glide slope capture logic.
-`lib_util.ks`: Added `utilTo360` function. It just make an arbitrary angle to fall into the 0-360 range. For example, -90 degres became 270.
-`node_hoh.ks`: Now it predicts the time to phi with precision, no more guesswork.
-`node_inc_equ.ks` and `node_inc_tgt.ks`: New component in prograde/retrograde direction prevents the orbit changing shape when changing inclination.
-`transfer.ks` and `warp.ks`: Adjustment in warp.
 
**Know issue/limitation**

-`node_hoh.ks` is only precise if orbits are almost exactly circular, specially with orbits that have a very large size difference.

**Comment by xeger** [comment]
Wow; I'm very happy to see that RAMP finally has some marketing! :-) Reviewing the code now.

**Comment by xeger** [comment]
FWIW, Hohmann has a fundamental limitation that your initial and final orbit are both circular. I haven't done much looking for alternatives.

**Review by xeger — APPROVED** [review]

**Comment by fellipec** [comment]
I'm glad to work on this. It's fun and I'm learning a lot!
If Hohmann transfers need to work only with circular orbits, well, then is not an issue with the code.
BTW today I made several tests and found a handful bugs. Worst ones are with logic of plane matching, specially when ship and target are in opposite sides of orbit, and my new Hohmann code was not working for transfer to lower orbits. Now I believe it's fixed. Also found a bug on landing code, forget to add time:seconds where it compute the deltaV to deorbit. Because orbits are kinda circular didn't manage to find that sooner. 

I'm committing to my branch those fixes, and I think tomorrow I'll livestream some demo of RAMP capabilities. I guess (and is only a wild guess) that now is possible to play any kind of mission in Kerbin, Mun and Minmus.

**Pull request merged**
